gui:
  nerdFontsVersion: "3"
  scrollHeight: 4
  scrollOffMargin: 4
os:
  editCommand: 'nvim --server $NVIM'
  editCommandTemplate: "{{editor}} --remote-send '<C-\\><C-n>:5ToggleTerm<CR>:lua _edit({{filename}}, {{line}})<CR>'"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
